'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

nmax = 4000000

# optimized version

def sum_fib_under(nmax):
    f1 = 1
    f2 = 1
    f3 = f1 + f2
    
    s = 0
    
    while f3 <= nmax:
        s += f3
        
        f1 = f3 + f2
        f2 = f3 + f1
        f3 = f1 + f2
        
    return s

print(sum_fib_under(nmax))